FROM python:3.12.6
WORKDIR /app
COPY ./OCR_BACK/requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*
RUN curl -o ./wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
COPY ./OCR_BACK .
EXPOSE 8000