
FROM python:3.12.6


RUN apt-get update && apt-get install -y poppler-utils


WORKDIR /app


COPY ./OCR_BACK/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY ./OCR_BACK .


EXPOSE 8000


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]